### ISSUE TITLE
70% CONCLUÍDO!!!

### ISSUE THREAD

**Issue by ItaloGostoso** [ItaloGostoso/Projeto-Linguagem-I#8]
Mais uma conquista do nosso grupo, é com grande alegria que informamos que já temos 70% do programa concluído. Agradecemos a todo o apoio recebido até o momento, por parte do nosso professor de Linguagem de Programação I, Breno Leonardo e por nos ensinar tudo o que sabemos sobre Java.

O nosso grupo permaneceu unido e focado, mesmo com problemas pessoais para resolver, todos os integrantes colaboraram no desenvolvimento do programa.

**Comment by luiziane-franca** [comment]
Sim Italo, focados conseguiremos terminar o projeto com sucesso.
